# GitHub Copilot Configuration

# This file configures GitHub Copilot behavior for this repository.
# Place this in .github/copilot.yml or follow GitHub's recommended location.

# For more information, see:
# https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot

# Project-specific context for Copilot
project_context: |
  This is a TypeScript + Node.js barcode scanner service using:
  - Strict TypeScript (ES2022, NodeNext modules)
  - ESLint with zero warnings policy
  - Prettier for code formatting
  - Conventional commits (commitlint)
  - Yarn Berry v4.10.3
  - Node.js v24.11.0

# Coding standards to enforce
coding_standards:
  typescript:
    - Use explicit return types for all functions
    - Never use 'any' type; use 'unknown' when type is uncertain
    - Use inline type imports: import { type Foo } from './bar.js'
    - Always include .js extension in imports, even for .ts files
    - Avoid non-null assertions (!); use type guards instead
    - Prefix unused parameters with underscore (_param)
  
  style:
    - Single quotes, semicolons always
    - 100 character line width
    - 2 space indentation, no tabs
    - LF line endings
    - Trailing commas ES5 style
    - Arrow functions always use parentheses
  
  code_quality:
    - Use strict equality (=== and !==)
    - Prefer const over let, never use var
    - Only console.warn and console.error allowed; use logger for other cases
    - Handle all promise rejections
    - Implement proper error handling, never silent failures
    - Clean up event listeners and timers
  
  architecture:
    - Follow established directory structure (config/, devices/, domain/, transport/, infra/, utils/)
    - Use camelCase for files, PascalCase for classes/types
    - Implement dependency injection for testability
    - Create specific error classes for different error types
    - Document public APIs with JSDoc

# Commit message format
commit_format:
  style: conventional_commits
  types:
    - feat      # New feature
    - fix       # Bug fix
    - docs      # Documentation only
    - style     # Code style (formatting, etc.)
    - refactor  # Code refactoring
    - perf      # Performance improvement
    - test      # Adding/updating tests
    - build     # Build system/dependencies
    - ci        # CI configuration
    - chore     # Other changes
    - revert    # Revert previous commit

# Common patterns to follow
patterns:
  error_handling: |
    class CustomError extends Error {
      constructor(message: string) {
        super(message);
        this.name = 'CustomError';
      }
    }
    
    try {
      await operation();
    } catch (error) {
      if (error instanceof CustomError) {
        logger.warn('Expected error', error);
        return;
      }
      throw error;
    }
  
  module_imports: |
    // Relative imports with .js extension
    import { type Foo, Bar } from './bar.js';
    
    // Node built-ins with node: prefix
    import { EventEmitter } from 'node:events';
    import * as path from 'node:path';
    
    // External packages
    import HID from 'node-hid';
  
  async_operations: |
    // Use async/await instead of promise chains
    async function connectDevice(id: string): Promise<void> {
      try {
        await discovery.find(id);
        await reader.open(id);
        logger.info('Connected');
      } catch (error) {
        logger.error('Connection failed', error);
        throw error;
      }
    }
  
  logging: |
    // Use logger, not console.log
    import { logger } from './infra/logger.js';
    
    logger.info('Info message');
    logger.warn('Warning message');
    logger.error('Error message', error);
    
    // Only console.warn and console.error allowed in exceptional cases
    console.warn('Direct warning');
    console.error('Direct error');

# Anti-patterns to avoid
anti_patterns:
  - Using 'any' type
  - Non-null assertions (!)
  - console.log (use logger instead)
  - Loose equality (== and !=)
  - var declarations
  - Missing file extensions in imports
  - Unhandled promise rejections
  - Silent error handling
  - Memory leaks (uncleaned listeners/timers)
  - Hardcoded configuration values
  - Missing return type declarations

# Security guidelines
security:
  - Validate all external inputs
  - Sanitize string inputs
  - Avoid logging sensitive data
  - Use type-safe parsing for unknown data
  - Handle errors without exposing internal details
  - Follow principle of least privilege
  - Keep dependencies updated

# Performance considerations
performance:
  - Manage buffers efficiently for HID data streams
  - Clean up event listeners and timers
  - Use appropriate data structures
  - Cache expensive computations when appropriate
  - Avoid unnecessary object allocations
  - Use async operations for I/O

# Documentation requirements
documentation:
  - JSDoc for all public APIs
  - Parameter descriptions with types
  - Return value descriptions
  - Throws clauses for errors
  - Usage examples for complex functions
  - Inline comments only for non-obvious logic

# Testing approach
testing:
  - Write testable code with dependency injection
  - Test happy path and error conditions
  - Test edge cases
  - Mock external dependencies
  - Use descriptive test names
  - Follow AAA pattern (Arrange, Act, Assert)

# Additional context files
reference_files:
  - .github/copilot-instructions.md  # Comprehensive guidelines
  - .github/ai-prompts.md            # Prompt templates and examples
  - GUIDELINES.md                     # Project technical guidelines
  - README.md                         # Project overview and setup
  - eslint.config.js                  # ESLint rules
  - .prettierrc                       # Prettier configuration
  - tsconfig.json                     # TypeScript configuration
  - commitlint.config.js              # Commit message rules
